<?php

namespace Database\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema as Schema;

class Version20210612100624 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema): void
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('DROP TABLE shop_image_tmp');
        $this->addSql('ALTER TABLE shop_image CHANGE updated_at updated_at DATETIME on update CURRENT_TIMESTAMP');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema): void
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE shop_image_tmp (id INT AUTO_INCREMENT NOT NULL, artikul CHAR(128) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, image VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, main TINYINT(1) DEFAULT NULL, name TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, name_pricelist VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, attribute_set_id SMALLINT DEFAULT NULL, img_tut VARCHAR(32) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, size_x SMALLINT UNSIGNED DEFAULT NULL, size_y SMALLINT UNSIGNED DEFAULT NULL, size_xy INT UNSIGNED DEFAULT NULL, size_tut INT UNSIGNED DEFAULT NULL, k_grey INT DEFAULT NULL, k_rgb_mix INT UNSIGNED DEFAULT NULL, size_tam INT DEFAULT NULL, entity_id INT DEFAULT NULL, skachan TINYINT(1) DEFAULT NULL, dop VARCHAR(32) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, is_in_stock TINYINT(1) DEFAULT NULL, postavshik INT DEFAULT NULL, k_1_1 INT DEFAULT NULL, k_2_1 INT DEFAULT NULL, k_3_1 INT DEFAULT NULL, k_1_2 INT DEFAULT NULL, k_2_2 INT DEFAULT NULL, k_3_2 INT DEFAULT NULL, k_1_3 INT DEFAULT NULL, k_2_3 INT DEFAULT NULL, k_3_3 INT DEFAULT NULL, k_1_4 INT DEFAULT NULL, k_2_4 INT DEFAULT NULL, k_3_4 INT DEFAULT NULL, k_1_5 INT DEFAULT NULL, k_2_5 INT DEFAULT NULL, k_3_5 INT DEFAULT NULL, k_1_6 INT DEFAULT NULL, k_2_6 INT DEFAULT NULL, k_3_6 INT DEFAULT NULL, k_1_7 INT DEFAULT NULL, k_2_7 INT DEFAULT NULL, k_3_7 INT DEFAULT NULL, k_1_8 INT DEFAULT NULL, k_2_8 INT DEFAULT NULL, k_3_8 INT DEFAULT NULL, k_1_9 INT DEFAULT NULL, k_2_9 INT DEFAULT NULL, k_3_9 INT DEFAULT NULL, k_1_10 INT DEFAULT NULL, k_2_10 INT DEFAULT NULL, k_3_10 INT DEFAULT NULL, k_1_11 INT DEFAULT NULL, k_2_11 INT DEFAULT NULL, k_3_11 INT DEFAULT NULL, k_1_12 INT DEFAULT NULL, k_2_12 INT DEFAULT NULL, k_3_12 INT DEFAULT NULL, k_1_13 INT DEFAULT NULL, k_2_13 INT DEFAULT NULL, k_3_13 INT DEFAULT NULL, k_1_14 INT DEFAULT NULL, k_2_14 INT DEFAULT NULL, k_3_14 INT DEFAULT NULL, k_1_15 INT DEFAULT NULL, k_2_15 INT DEFAULT NULL, k_3_15 INT DEFAULT NULL, k_1_16 INT DEFAULT NULL, k_2_16 INT DEFAULT NULL, k_3_16 INT DEFAULT NULL, ott_0 INT DEFAULT NULL, ott_1 INT DEFAULT NULL, ott_2 INT DEFAULT NULL, ott_3 INT DEFAULT NULL, ott_4 INT DEFAULT NULL, ott_5 INT DEFAULT NULL, ott_6 INT DEFAULT NULL, ott_7 INT DEFAULT NULL, ott_8 INT DEFAULT NULL, ott_9 INT DEFAULT NULL, ott_10 INT DEFAULT NULL, ott_11 INT DEFAULT NULL, ott_12 INT DEFAULT NULL, ott_13 INT DEFAULT NULL, ott_14 INT DEFAULT NULL, ott_15 INT DEFAULT NULL, ott_16 INT DEFAULT NULL, ott_17 INT DEFAULT NULL, ott_18 INT DEFAULT NULL, ott_19 INT DEFAULT NULL, ott_20 INT DEFAULT NULL, ott_21 INT DEFAULT NULL, ott_22 INT DEFAULT NULL, ott_23 INT DEFAULT NULL, ott_24 INT DEFAULT NULL, ott_25 INT DEFAULT NULL, ott_26 INT DEFAULT NULL, ott_27 INT DEFAULT NULL, ott_28 INT DEFAULT NULL, ott_29 INT DEFAULT NULL, ott_30 INT DEFAULT NULL, ott_31 INT DEFAULT NULL, ott_32 INT DEFAULT NULL, ott_33 INT DEFAULT NULL, ott_34 INT DEFAULT NULL, ott_35 INT DEFAULT NULL, ott_36 INT DEFAULT NULL, ott_37 INT DEFAULT NULL, ott_38 INT DEFAULT NULL, ott_39 INT DEFAULT NULL, ott_40 INT DEFAULT NULL, ott_41 INT DEFAULT NULL, ott_42 INT DEFAULT NULL, ott_43 INT DEFAULT NULL, ott_44 INT DEFAULT NULL, ott_45 INT DEFAULT NULL, ott_46 INT DEFAULT NULL, ott_47 INT DEFAULT NULL, ott_48 INT DEFAULT NULL, ott_49 INT DEFAULT NULL, ott_50 INT DEFAULT NULL, ott_51 INT DEFAULT NULL, ott_52 INT DEFAULT NULL, ott_53 INT DEFAULT NULL, ott_54 INT DEFAULT NULL, ott_55 INT DEFAULT NULL, ott_56 INT DEFAULT NULL, ott_57 INT DEFAULT NULL, ott_58 INT DEFAULT NULL, ott_59 INT DEFAULT NULL, ott_60 INT DEFAULT NULL, ott_61 INT DEFAULT NULL, ott_62 INT DEFAULT NULL, ott_63 INT DEFAULT NULL, upakovka VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX artikul (artikul), INDEX postavshik (postavshik), INDEX shop_image_tmp_entity_id_index (entity_id), INDEX te_set_id_postavshik_index (attribute_set_id, postavshik), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE shop_image CHANGE updated_at updated_at DATETIME DEFAULT NULL');
    }
}
